# Generated by Django 5.1.7 on 2025-03-22 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationrequest',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='certificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificationrequest',
            name='submitted_documents',
            field=models.FileField(upload_to='certification_documents/'),
        ),
    ]
